apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-service
  namespace: eventhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: participant-service
  template:
    metadata:
      labels:
        app: participant-service
    spec:
      containers:
      - name: participant-service
        image: mariaa04/eventhub-participant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        
        volumeMounts:
        - name: media-volume
          mountPath: /app/media          # Chemin où Django va stocker les fichiers (images, etc.)
      
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: eventhub-files-pvc