apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-service
  namespace: eventhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: participant-service
  template:
    metadata:
      labels:
        app: participant-service
    spec:
      containers:
      - name: participant-service
        image: mmajora53/eventhub-participant:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "True"