apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-service
  namespace: eventhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: participant-service
  template:
    metadata:
      labels:
        app: participant-service
    spec:
      containers:
      - name: participant-service
        image: claraaitm/eventhub-participant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password