apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventhub-files-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host/eventhub-files"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventhub-files-pvc
  namespace: eventhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi