# Generated by Django 5.1.5 on 2026-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
